version: 2.0
services:
  default: !include sonic_services.yaml
params: !include sonic_params.yaml
builds: !include sonic_builds.yaml
speeds: !include sonic_speeds.yaml
errors: !include sonic_errors.yaml
instrument: !include sonic_instrument.yaml
configs: !include sonic_configs_all.yaml
overrides:
  services:
    default:
      snmptrap:
        ip: 127.0.0.1
        username: ubuntu
        password: ubuntu
devices:
  V3:
    device_type: sonicvs
    access:
      protocol: telnet
      ip: 127.0.0.1
      port: 7003
    rps:
      model: virsh
      ip: 127.0.0.1
      port: 22
      outlet: V3
      username: ubuntu
      password: ubuntu
    credentials:
      username: admin
      password: YourPaSsWoRd
      altpassword: broadcom
    properties:
      config: default
      build: default
      services: default
      params: def_dut
      speed: default
    params:
      chip: VS
  V4:
    device_type: sonicvs
    access:
      protocol: telnet
      ip: 127.0.0.1
      port: 7004
    rps:
      model: virsh
      ip: 127.0.0.1
      port: 22
      outlet: V4
      username: ubuntu
      password: ubuntu
    credentials:
      username: admin
      password: YourPaSsWoRd
      altpassword: broadcom
    properties:
      config: default
      build: default
      services: default
      params: def_dut
      speed: default
    params:
      chip: VS
  tgen-01:
    device_type: TGEN
    properties:
      type: scapy
      version: 1.0
      ip: 127.0.0.1
      virtual: 1
      console: None
topology:
  V3:
    interfaces:
      Ethernet16:
        reserved: true
      Ethernet20:
        reserved: true
      Ethernet24:
        reserved: true
      Ethernet28:
        reserved: true
      Ethernet32:
        reserved: true
      Ethernet36:
        reserved: true
      Ethernet40:
        reserved: true
      Ethernet44:
        reserved: true
      Ethernet0:
        EndDevice: tgen-01
        EndPort: 1/9
      Ethernet4:
        EndDevice: tgen-01
        EndPort: 1/10
      Ethernet8:
        EndDevice: tgen-01
        EndPort: 1/11
      Ethernet12:
        EndDevice: tgen-01
        EndPort: 1/12
      Ethernet48:
        EndDevice: V4
        EndPort: Ethernet48
      Ethernet52:
        EndDevice: V4
        EndPort: Ethernet52
      Ethernet56:
        EndDevice: V4
        EndPort: Ethernet56
      Ethernet60:
        EndDevice: V4
        EndPort: Ethernet60
      Ethernet64:
        EndDevice: V4
        EndPort: Ethernet64
      Ethernet68:
        EndDevice: V4
        EndPort: Ethernet68
  V4:
    interfaces:
      Ethernet16:
        reserved: true
      Ethernet20:
        reserved: true
      Ethernet24:
        reserved: true
      Ethernet28:
        reserved: true
      Ethernet32:
        reserved: true
      Ethernet36:
        reserved: true
      Ethernet40:
        reserved: true
      Ethernet44:
        reserved: true
      Ethernet0:
        EndDevice: tgen-01
        EndPort: 1/13
      Ethernet4:
        EndDevice: tgen-01
        EndPort: 1/14
      Ethernet8:
        EndDevice: tgen-01
        EndPort: 1/15
      Ethernet12:
        EndDevice: tgen-01
        EndPort: 1/16
